
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Vista
 */
public class Main extends javax.swing.JFrame {
    private String name = "";
    private String role = "";
    String bookTableTitle = "Id \tName \tCategory \tprice \n --------------------------------------------------------------------------------------- \n";
    String UserTableTitle = "Name \tUsername \tRole \n --------------------------------------------------------------------------------------- \n";

    /** Creates new form Dashboard */
    public Main() {
        initComponents();
        initialSetup();
    }

    public Main(String name, String role) {
        this.name = name;
        this.role = role;

        initComponents();
        initialSetup();
    }
    
    private void initialSetup () {
        Book books = new Book();
        
        txtUsername.setText(name);
        txtaBooks.setText(bookTableTitle + books.viewAllBooks());
        txtBookId.setText((books.getBookCount()+1) + "");
        
        if (!this.role.equals("MANAGER")) {
            tabbedPane.remove(1);
        } else {
            User users = new User();
            txtaUsers.setText(UserTableTitle + users.viewAllUsers());
        }
    }
    
    private void refreshDashboard () {
        Book books = new Book();
        
        txtaBooks.setText(bookTableTitle + books.viewAllBooks());
        txtBookId.setText((books.getBookCount()+1) + "");

        txtBookname.setText("");
        txtBookcategory.setText("");
        txtBookPrice.setText("");
        
        if (this.role.equals("MANAGER")) {
            User users = new User();

            txtaUsers.setText(UserTableTitle + users.viewAllUsers());
            
            txtNewUserName.setText("");
            txtNewUserUsername.setText("");
            txtNewUserPassword.setText("");
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tabbedPane = new javax.swing.JTabbedPane();
        pBooks = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSearchBar = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtaBooks = new javax.swing.JTextArea();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBookId = new javax.swing.JTextField();
        txtBookname = new javax.swing.JTextField();
        txtBookcategory = new javax.swing.JTextField();
        txtBookPrice = new javax.swing.JTextField();
        btnNewBook = new javax.swing.JButton();
        pUsers = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtaUsers = new javax.swing.JTextArea();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        txtNewUserName = new javax.swing.JTextField();
        txtNewUserUsername = new javax.swing.JTextField();
        txtNewUserPassword = new javax.swing.JPasswordField();
        cmbNewuserRole = new javax.swing.JComboBox<>();
        btnAddNewUser = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtUsername = new javax.swing.JLabel();
        btnLogout = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 50));
        setResizable(false);

        jLabel4.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel4.setText("Manage Books");

        btnSearch.setText("Search");
        btnSearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSearchActionPerformed(evt);
            }
        });

        txtaBooks.setColumns(20);
        txtaBooks.setFont(txtaBooks.getFont());
        txtaBooks.setRows(5);
        txtaBooks.setFocusable(false);
        jScrollPane1.setViewportView(txtaBooks);

        jLabel5.setText("Add a new Book");

        jLabel6.setText("Book ID");

        jLabel7.setText("Name");

        jLabel8.setText("Category");

        jLabel9.setText("Price");

        txtBookId.setFocusable(false);

        txtBookcategory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtBookcategoryActionPerformed(evt);
            }
        });

        btnNewBook.setText("Add book");
        btnNewBook.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNewBookActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pBooksLayout = new javax.swing.GroupLayout(pBooks);
        pBooks.setLayout(pBooksLayout);
        pBooksLayout.setHorizontalGroup(
            pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBooksLayout.createSequentialGroup()
                .addContainerGap(133, Short.MAX_VALUE)
                .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(170, 170, 170))
            .addGroup(pBooksLayout.createSequentialGroup()
                .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pBooksLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1))
                    .addGroup(pBooksLayout.createSequentialGroup()
                        .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(pBooksLayout.createSequentialGroup()
                                .addGap(262, 262, 262)
                                .addComponent(jLabel4))
                            .addGroup(pBooksLayout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel9))
                                .addGap(46, 46, 46)
                                .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtBookId)
                                    .addComponent(txtBookname)
                                    .addComponent(txtBookcategory)
                                    .addComponent(txtBookPrice, javax.swing.GroupLayout.DEFAULT_SIZE, 213, Short.MAX_VALUE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pBooksLayout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(btnNewBook, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pBooksLayout.createSequentialGroup()
                .addGap(258, 258, 258)
                .addComponent(jLabel5)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pBooksLayout.setVerticalGroup(
            pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pBooksLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearchBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSearch))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtBookId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(txtBookname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txtBookcategory, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pBooksLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtBookPrice, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnNewBook)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        tabbedPane.addTab("Books", pBooks);

        txtaUsers.setColumns(20);
        txtaUsers.setRows(5);
        txtaUsers.setFocusable(false);
        jScrollPane2.setViewportView(txtaUsers);

        jLabel10.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 12)); // NOI18N
        jLabel10.setText("Manage Users");

        jLabel11.setText("Add a new User");

        jLabel12.setText("Name");

        jLabel13.setText("Username");

        jLabel14.setText("Password");

        jLabel15.setText("Role");

        txtNewUserUsername.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewUserUsernameActionPerformed(evt);
            }
        });

        cmbNewuserRole.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "MANAGER", "CASHIER" }));

        btnAddNewUser.setText("Add User");
        btnAddNewUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddNewUserActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pUsersLayout = new javax.swing.GroupLayout(pUsers);
        pUsers.setLayout(pUsersLayout);
        pUsersLayout.setHorizontalGroup(
            pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsersLayout.createSequentialGroup()
                .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUsersLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2))
                    .addGroup(pUsersLayout.createSequentialGroup()
                        .addGap(268, 268, 268)
                        .addComponent(jLabel10)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(pUsersLayout.createSequentialGroup()
                .addGap(145, 145, 145)
                .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pUsersLayout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addComponent(jLabel11))
                    .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(btnAddNewUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(pUsersLayout.createSequentialGroup()
                            .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel12)
                                .addComponent(jLabel13)
                                .addComponent(jLabel14)
                                .addComponent(jLabel15))
                            .addGap(41, 41, 41)
                            .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNewUserName)
                                .addComponent(txtNewUserUsername)
                                .addComponent(txtNewUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(cmbNewuserRole, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        pUsersLayout.setVerticalGroup(
            pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pUsersLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addGap(25, 25, 25)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 26, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(18, 18, 18)
                .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtNewUserName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txtNewUserUsername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(txtNewUserPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(pUsersLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(cmbNewuserRole, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnAddNewUser)
                .addContainerGap())
        );

        tabbedPane.addTab("Users", pUsers);

        jLabel1.setFont(new java.awt.Font("Arial Rounded MT Bold", 0, 18)); // NOI18N
        jLabel1.setText("City Book Shop");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel2.setText("Welcome back,");

        txtUsername.setFont(new java.awt.Font("Forte", 0, 18)); // NOI18N
        txtUsername.setText("name");

        btnLogout.setBackground(new java.awt.Color(255, 204, 204));
        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtUsername)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(242, 242, 242)
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addComponent(tabbedPane)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtUsername)
                    .addComponent(btnLogout))
                .addGap(18, 18, 18)
                .addComponent(tabbedPane)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtBookcategoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtBookcategoryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtBookcategoryActionPerformed

    private void txtNewUserUsernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewUserUsernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNewUserUsernameActionPerformed

    private void btnNewBookActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNewBookActionPerformed
        if (txtBookname.getText().isEmpty() || txtBookcategory.getText().isEmpty() || txtBookPrice.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null,"Fileds cannot be empty, When adding a new book." ,"Add a new Book", JOptionPane.WARNING_MESSAGE);
        } else {
            int id = Integer.parseInt(txtBookId.getText());
            String name = txtBookname.getText();
            String category = txtBookcategory.getText();
            float price = Float.parseFloat( txtBookPrice.getText());
            
            Book newBook = new Book(id,name,category,price);
            
            if (newBook.addNewBook()) {
                JOptionPane.showMessageDialog(null,"Book Added successfully" ,"Add a new Book", JOptionPane.INFORMATION_MESSAGE);
                refreshDashboard();
            } else {
                JOptionPane.showMessageDialog(null,"Sorry! Something went wrong with the application, Will be fixing it soon." ,"Add a new Book", JOptionPane.WARNING_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnNewBookActionPerformed

    private void btnSearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSearchActionPerformed
        String keyword = txtSearchBar.getText();
        
        if (keyword.isEmpty()) {
            refreshDashboard();
        } else {
            Book book = new Book();
            
            if (book.searchbook(keyword)) {
                txtaBooks.setText(bookTableTitle + book.getId() + "\t" + book.getName() + "\t" + book.getCategory() + "\t" + book.getPrice());
            } else {
                JOptionPane.showMessageDialog(null,"Sorry! We do not have any matching books" ,"Search a book", JOptionPane.INFORMATION_MESSAGE);
            }
        }
    }//GEN-LAST:event_btnSearchActionPerformed

    private void btnAddNewUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddNewUserActionPerformed
        if (!this.role.equals("MANAGER")) {
            JOptionPane.showMessageDialog(null,"You do have the rights to add a new user" ,"Unauthorised", JOptionPane.ERROR_MESSAGE);
        } else {
            if (txtNewUserName.getText().isEmpty() || txtNewUserUsername.getText().isEmpty() || txtNewUserPassword.getText().isEmpty()) {
                JOptionPane.showMessageDialog(null,"Fileds cannot be empty, When adding a new User." ,"Add a new User", JOptionPane.WARNING_MESSAGE);
            } else {
                String name = txtNewUserName.getText();
                String username = txtNewUserUsername.getText();
                String password = txtNewUserPassword.getText();
                String role = cmbNewuserRole.getSelectedItem().toString();

                User newUser = new User(name,username,password,role);

                if (newUser.addNewUser()) {
                    JOptionPane.showMessageDialog(null,"User Added successfully" ,"Add a new User", JOptionPane.INFORMATION_MESSAGE);
                    refreshDashboard();
                } else {
                    JOptionPane.showMessageDialog(null,"Sorry! Something went wrong with the application, Will be fixing it soon." ,"Add a new User", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnAddNewUserActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
       Login login = new Login();
       login.show();
       
       this.dispose();
    }//GEN-LAST:event_btnLogoutActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddNewUser;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnNewBook;
    private javax.swing.JButton btnSearch;
    private javax.swing.JComboBox<String> cmbNewuserRole;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JPanel pBooks;
    private javax.swing.JPanel pUsers;
    private javax.swing.JTabbedPane tabbedPane;
    private javax.swing.JTextField txtBookId;
    private javax.swing.JTextField txtBookPrice;
    private javax.swing.JTextField txtBookcategory;
    private javax.swing.JTextField txtBookname;
    private javax.swing.JTextField txtNewUserName;
    private javax.swing.JPasswordField txtNewUserPassword;
    private javax.swing.JTextField txtNewUserUsername;
    private javax.swing.JTextField txtSearchBar;
    private javax.swing.JLabel txtUsername;
    private javax.swing.JTextArea txtaBooks;
    private javax.swing.JTextArea txtaUsers;
    // End of variables declaration//GEN-END:variables
}
